project-name: Portfolio
base-path: /
context:
  static:
    author: Dennis Peter
    website: https://www.dennohpeter.com
    mail: denispeterson96@gmail.com
    github: https://github.com/dennohpeter
    gitlab: https://gitlab.com/dennohpeter
    twitter: https://twitter.com/dennohpeter
    devpost: https://devpost.com/dennohpeter
    codewars: ""
    stackoverlow: ""
